### ISSUE TITLE
启动太慢了，ssr没效果

### ISSUE THREAD

**Issue by qyd159** [easy-temps/nuxt-vant-mobile#1]

**Comment by cwandev** [comment]
感谢反馈！SSR 没效果 和 color-mode 包提供的 ColorScheme 组件有关系，稍晚些我看看怎么处理。

**Comment by qyd159** [comment]
期待能尽快解决这问题，ok的话，我会将项目迁移过来，ssr对用户体验太重要了，后面可以参与贡献

**Comment by cwandev** [comment]
今晚我会发布一个小版本

**Comment by cwandev** [comment]
已发布 ! 

>  https://github.com/easy-temps/nuxt-vant-mobile/releases/tag/v0.2.0
